PREFIX ?= rl78-elf-

CC      = $(PREFIX)gcc
AS      = $(PREFIX)as
OBJCOPY = $(PREFIX)objcopy
OBJDUMP = $(PREFIX)objdump

NAME    = sa8x8-fw

.PHONY: all
all: sa868s_vhf sa868s_350 sa868s_uhf

.PHONY: sa868s_vhf
sa868s_vhf: MODEL = SA868S-VHF
sa868s_vhf: rl78

.PHONY: sa868s_350
sa868s_350: MODEL = SA868S-350
sa868s_350: rl78

.PHONY: sa868s_uhf
sa868s_uhf: MODEL = SA868S-UHF
sa868s_uhf: rl78

CFLAGS_RL78  = \
	  -Isrc -g -Os --param=min-pagesize=0 -mcpu=g13 \
	  -ffunction-sections \
	  -fdata-sections \
	  -fdiagnostics-parseable-fixits \
	  -Wunused \
	  -Wuninitialized \
	  -Wall \
	  -Wextra \
	  -Wmissing-declarations \
	  -Wconversion \
	  -Wpointer-arith \
	  -Wshadow \
	  -Waggregate-return

LDFLAGS_RL78 = \
	  -nostartfiles \
	  -Wl,-z,noexecstack \
	  -Wl,-e_PowerOnReset \
	  -Wl,--gc-sections \
	  -Wl,--cref \
	  -Wl,-Map,$(TARGET).map \
	  -T ./src/r5f1026a/r5f1026a.ld

OBJECTS_RL78 = \
	src/r5f1026a/start.o \
	src/r5f1026a/vectors.o \
	src/r5f1026a/interrupts.o \
	src/r5f1026a/platform.o \
	src/sa8x8.o

GIT_DIR ?= .git
ifneq ($(and $(wildcard $(GIT_DIR)),$(shell which git)),)
	GIT_INFO = $(shell git describe --long --tags --abbrev=7 | sed 's/\([^-]*-g\)/r\1/;s/-/./g')
else
	GIT_INFO = "unknown"
endif

OUTPUTS = \
	$(TARGET).elf \
	$(TARGET).bin \
	$(TARGET).s37

VERSION_HEADER = src/version.h

.PHONY: $(VERSION_HEADER)
$(VERSION_HEADER):
	@echo "Creating $@ for $(MODEL)"
	@echo "/*" > $@
	@echo " * This file is automatically generated. Do not edit." >> $@
	@echo " */" >> $@
	@echo "" >> $@
	@echo "#ifndef VERSION_H" >> $@
	@echo "#define VERSION_H" >> $@
	@echo "" >> $@
	@echo "#define GIT_INFO \"$(GIT_INFO)\"" >> $@
	@echo "" >> $@
	@echo "#define MODULE_MODEL \"$(MODEL)\"" >> $@
	@echo "" >> $@
	@echo "#endif" >> $@

src/sa8x8.o: $(VERSION_HEADER)

$(TARGET).elf: $(VERSION_HEADER) $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $(TARGET).elf

$(TARGET).bin: $(TARGET).elf
	$(OBJCOPY) -O binary $(TARGET).elf $(TARGET).bin

$(TARGET).s37: $(TARGET).elf
	$(OBJCOPY) -O srec --srec-forceS3 --srec-len 32 $(TARGET).elf $(TARGET).s37

LOWER   = $(shell echo '$1' | tr '[:upper:]' '[:lower:]')

.PHONY: rl78
rl78: TARGET   = $(NAME)-$(call LOWER,$(MODEL))
rl78: OBJECTS  = $(OBJECTS_RL78)
rl78: CFLAGS  += $(CFLAGS_RL78)
rl78: LDFLAGS += $(LDFLAGS_RL78)
rl78: $(OBJECTS_RL78)
rl78: common

.PHONY: common
common: $(VERSION_HEADER)
common: $(OUTPUTS)

.PHONY: clean
clean:
	rm -f $(OBJECTS_RL78) $(VERSION_HEADER)
	rm -f *.elf *.bin *.s37 *.map


