PREFIX ?= rl78-elf-

CC      = $(PREFIX)gcc
AS      = $(PREFIX)as
OBJCOPY = $(PREFIX)objcopy
OBJDUMP = $(PREFIX)objdump

TARGET  = sa8x8-fw

CFLAGS  = -Isrc -g -Os --param=min-pagesize=0 -mcpu=g13 -mmul=g10 \
	  -ffunction-sections \
	  -fdata-sections \
	  -fdiagnostics-parseable-fixits \
	  -Wunused \
	  -Wuninitialized \
	  -Wall \
	  -Wextra \
	  -Wmissing-declarations \
	  -Wconversion \
	  -Wpointer-arith \
	  -Wshadow \
	  -Waggregate-return

LDFLAGS = -nostartfiles -static-libgcc -lgcc \
	  -Wl,-Map,$(TARGET).map \
	  -Wl,--start-group \
	  -Wl,--end-group \
	  -Wl,-z,noexecstack \
	  -Wl,-e_PowerOnReset \
	  -Wl,--gc-sections \
	  -Wl,--cref \
	  -T ./src/r5f1026a/r5f1026a.ld

GIT_DIR ?= .git
ifneq ($(and $(wildcard $(GIT_DIR)),$(shell which git)),)
	GIT_HASH = $(shell git describe --always --dirty)
else
	GIT_HASH = "unknown"
endif

VERSION_HEADER = src/version.h

OBJECTS = \
	src/r5f1026a/start.o \
	src/r5f1026a/vectors.o \
	src/r5f1026a/interrupts.o \
	src/r5f1026a/platform.o \
	src/sa8x8.o

OUTPUTS = \
	$(TARGET).elf \
	$(TARGET).map \
	$(TARGET).bin \
	$(TARGET).s37

all: $(OUTPUTS)

$(VERSION_HEADER):
	@echo "Creating $@"
	@echo "/*" > $@
	@echo " * This file is automatically generated. Do not edit." >> $@
	@echo " */" >> $@
	@echo "" >> $@
	@echo "#ifndef VERSION_H" >> $@
	@echo "#define VERSION_H" >> $@
	@echo "" >> $@
	@echo "#define GIT_HASH \"$(GIT_HASH)\"" >> $@
	@echo "" >> $@
	@echo "#endif" >> $@

$(OBJECTS): $(VERSION_HEADER)

$(TARGET).elf: $(OBJECTS)
	$(CC) $(LDFLAGS) $(OBJECTS) -o $(TARGET).elf

$(TARGET).bin: $(TARGET).elf
	$(OBJCOPY) -O binary $(TARGET).elf $(TARGET).bin

$(TARGET).s37: $(TARGET).elf
	$(OBJCOPY) -O srec --srec-forceS3 --srec-len 32 $(TARGET).elf $(TARGET).s37

clean:
	rm -f $(OBJECTS) $(OUTPUTS) $(VERSION_HEADER) $(VERSION_OBJ)

.PHONY: all clean

