name: Build sa8x8-fw

on:
  push:
    paths:
      - src/**
  pull_request:
    paths:
      - src/**

env:
  SIF: https://github.com/OpenRTX/sa8x8-fw/releases/download/v1.0.0/rl78-elf-toolchain.sif
  TARGETS: sa818s_vhf sa818s_uhf sa868s_vhf sa868s_uhf

jobs:
  build:
    name: Generate firmware artifacts

    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.6

      - name: Compile
        run: |
          for T in $TARGETS
          do
            apptainer run $SIF make $T
          done

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: sa8x8-fw-srecs
          path: |
            ${{github.workspace}}/sa8x8-fw-*.s37

